apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-cors-proxy-hpa
  namespace: default # Or the namespace where your deployment is
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-cors-proxy # Must match the name of your Deployment
  minReplicas: 1 # Minimum number of pods to maintain, even under low load
  maxReplicas: 25 # Maximum number of pods to scale up to
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Target 50% average CPU utilization
