apiVersion: v1
kind: Service
metadata:
  name: mock-target-server-service # This will be the DNS name your proxy uses
  labels:
    app: mock-target-server
spec:
  selector:
    app: mock-target-server
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on within the cluster
      targetPort: 3000 # The port the container is listening on (json-server's default)
  type: ClusterIP # Internal service only
